### PR TITLE
Bump version (DSL change)

### PR DESCRIPTION
**Pull request by syntaxritual**

### CODE REVIEW

**Comment by rodrigosaito** [comment]
0.0.2 was not released yet, should we really bump the version to 0.0.3? Or would be better 0.1.0?

**Comment by syntaxritual** [comment]
Whatever you prefer... I was just incrementing what was there. :)

**Comment by rodrigosaito** [comment]
Then change it to 0.1.0, cause we introduced a breaking change.

On Tue, Jan 20, 2015 at 10:57 AM, Travis Anderson notifications@github.com
wrote:

> Whatever you prefer... I was just incrementing what was there. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rodrigosaito/roar-sinatra/pull/5#issuecomment-70649261
> .

## 

Rodrigo Saito
gtalk: rodrigo.saito@gmail.com
skype: rodrigo.saito

**Comment by syntaxritual** [comment]
Cool, it's out there

**Comment by rodrigosaito** [comment]
Pulled in

**Pull request merged**
