### PR TITLE
handle decorator classes and module namespaces

### PR DESCRIPTION
**Pull request by kmussel**

### CODE REVIEW

**Comment by syntaxritual** [comment]
:+1: This seems like it could be two separate pull requests... @rodrigosaito, thoughts?

**Comment by rodrigosaito** [comment]
I think just this one PR is ok.

Can you rebase this against master?

**Comment by syntaxritual** [comment]
(bump) @kmussel can you rebase this against master? :)

**Comment by kmussel** [comment]
Ok done

**Comment by rodrigosaito** [comment]
Thanks

**Pull request merged**
